version: '2'
services:
    rdvmaster-app:
        image: rdvmaster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rdvmaster-mysql:3306/rdvmaster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rdvmaster-mysql:
        extends:
            file: mysql.yml
            service: rdvmaster-mysql
